### ISSUE TITLE
Was there ever a resolution to this?

### ISSUE THREAD

**Issue by coffenbacher** [timoisalive/expo-app-auth-test#1]
We're seeing exactly the same issue on SDK32

**Comment by timoisalive** [comment]
@coffenbacher No resolution, we ended up forgetting Expo, although this probably could have been solved somehow...

**Comment by coffenbacher** [comment]
Ah, thanks. FWIW since I posted this, I tested it with the Expo 'bare' workflow and the new version of expo-app-auth is working in React Native projects. I am hoping Expo SDK33 is fixed, whatever the problem was.
